# Generated by Django 4.2.7 on 2026-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=50),
        ),
    ]
