# Generated by Django 4.2.7 on 2026-01-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_phone'),
    ]

    operations = [
    ]
